version: 6

system:
#  devices: 'auto'
#  strategy: 'auto',
  

data:
  # num_workers: 0 # no worker spawned for debugging
  num_workers: 8
  samples: [
    "/home/jwu/projects/63_hcs-image-analysis/42-incucyte/sample.yaml"
  ]
  inputs: ["images"]
  labels: ["label"]
  training: [
    "s01",
  ]
  validation: [
    "s01",
  ]
  test: [ # not used in training
  ]

model:
  name: 'LitSemanticRSUNet'
  in_channels: 2
  out_channels: 1
  kernel_size: [1, 3, 3]

train:
  preload: ""
  iter_start: 0
  iter_stop: 1000
  start_saving: 100000
  class_rebalance: false
  # batch size per GPU
  # The dataprovider should provide nGPU*batch_size batches!
  batch_size: 1
  log_dir: "./"
  patch_size: [1, 128, 128]
  learning_rate: 0.001
  training_interval: 200
  validation_interval: 2000
  #training_interval: 2
  #validation_interval: 4
