system:
  cpus: 4
  gpus: 1
  seed: 1

dataset:
  glob_path: "/mnt/ceph/users/neuro/wasp_em/jwu/40_gt/21_wasp_synapses/sample[1,2,3]/vol_*/syns_zyx_*.h5"
  validation_names: ["sample3/vol_01920"]
  test_names: ["sample3/vol_03680"]
  sample_name_to_image_versions: {
    sample1: [
      "/mnt/ceph/users/neuro/wasp_em/ykreinin/sample_1.7/3.contrast",
      "/mnt/ceph/users/neuro/wasp_em/jwu//sample1/04_image"
    ],
    sample2: [
      "/mnt/ceph/users/neuro/wasp_em/ykreinin/sample_2.1/3.contrast"
    ],
    sample3: [
      "/mnt/ceph/users/neuro/wasp_em/jwu/sample3/05_yuri_v3",
      "/mnt/ceph/users/neuro/wasp_em/jwu/sample3/07_yuri_v5",
      "/mnt/ceph/users/neuro/wasp_em/jwu/sample3/04_clahe"
    ]
  }

model:
  in_channels: 1
  out_channels: 1

train:
  iter_start: 2000000
  iter_stop: 8000000
  output_dir: "./"
  patch_size: [128, 128, 128]
  learning_rate: 0.001
  training_interval: 500
  validation_interval: 5000
