system:
  cpus: 1
  gpus: 1
  seed: 1



dataset:
  training:
    s3vol01700:
      images: ["/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/13_sample3/vol_01700/affs_160k.h5",] 
      label: "/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/13_sample3/vol_01700/label_v3.h5"
    s3vol02299:
      images: ["/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/13_sample3/vol_02299/affs_03_160k.h5",]      
      label: "/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/13_sample3/vol_02299/label_v4.h5"   
    s3vol03290:
      images: ["/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/13_sample3/vol_03290/affs_03_160k.h5",] 
      label: "/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/13_sample3/vol_03290/label_v2.h5"
    s3vol03700: 
      images: ["/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/13_sample3/vol_03700/affs_03_160k.h5",]
      label: "/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/13_sample3/vol_03700/label_v3.h5"
    s3vol04900:
      images: ["/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/13_sample3/vol_04900/affs_160k.h5",] 
      label: "/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/13_sample3/vol_04900/label_v4.h5"
    s3vol05250:
      images: ["/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/13_sample3/vol_05250/affs_03_160k.h5",] 
      label: "/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/13_sample3/vol_05250/label_v3.h5"
    s3vol05450:
      images: ["/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/13_sample3/vol_05450/affs_160k.h5",] 
      label: "/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/13_sample3/vol_05450/label_v4.h5"
  
  validation:
    s3test1:
      images: ["/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/58_broken_membrane/31_test_3072-3584_5120-5632_8196-8708/aff_zyx_3072-3584_5120-5632_8196-8708.h5",]
    s3test2: 
      images: ["/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/58_broken_membrane/32_test_5120-5632_5632-6144_10240-10752/aff_zyx_5120-5632_5632-6144_10240-10752.h5",]
    s3test3:
      images: ["/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/58_broken_membrane/33_test_2560-3072_5632-6144_8704-9216/aff_zyx_2560-3072_5632-6144_8704-9216.h5",]
    s3test4:
      images: ["/users/Manny/OneDrive/Documents/SimonsCCNNCA/Volumes/58_broken_membrane/41_test_2560-3584_5120-6144_8192-9216/aff_zyx_2560-3584_5120-6144_8192-9216.h5",]
      
model:
  in_channels: 3
  out_channels: 3

train:
  iter_start: 0
  iter_stop: 100000
  class_rebalance: True
  # batch size per GPU
  # The dataprovider should provide nGPU*batch_size batches!
  batch_size: 1
  output_dir: "./"
  patch_size: [128, 128, 128]
  learning_rate: 0.001
  training_interval: 2000
  validation_interval: 4000
  #training_interval: 2 
  #validation_interval: 4

